### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by Maaack** [jnbt/google-idtoken-verifier#1]
Got this error message when trying to connect:

Google::Idtoken::Verifier::Error: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

I'm running ruby 2.2.3 (upgraded from 2.2.1 to try to resolve it, but no luck)

Found this post: https://gist.github.com/luislavena/f064211759ee0f806c88
Could be helpful for a fix.

**Comment by jnbt** [comment]
Hi @Maaack,

sorry for not coming back earlier to this issue. Thanks for the information about the SSL error. 

My conclusions:
- Ruby 2.2.1 -> SSL error
- Ruby 2.2.2 -> SSL error
- Ruby 2.2.3 -> works
- Ruby 2.2.4 -> works
- Ruby 2.3.0 -> works

I'll check for a fix.

**Comment by jnbt** [comment]
It's a little bit strange as it works on Travis CI for Ruby 2.2.1 and 2.2.2. 

As far as I understood the problem Travis CI has already updated / patched the OpenSSL used for Ruby.

**Comment by jnbt** [comment]
So I was able to fix this issue on my machine, by simple reinstalling the Ruby versions. 

I'm using RVM, so it was simple as: `rvm reinstall 2.2.2 --disable-binary`

@Maaack Is this a working solution for you?

**Comment by Maaack** [comment]
Thanks for getting back to me! I was trying to remember how I resolved this issue as soon as you responded, but didn't have time to dig into it. Your solution was also what worked for me. I ended up reinstalling Ruby from scratch to get it to work.

**Comment by Maaack** [comment]
I'll mark this issue closed. Thanks again!
